### Cross Validation

Write a Python function that performs k-fold cross-validation data splitting from scratch. The function should take a dataset (as a 2D NumPy array where each row represents a data sample and each column represents a feature) and an integer k representing the number of folds. The function should split the dataset into k parts, systematically use one part as the test set and the remaining as the training set, and return a list where each element is a tuple containing the training set and test set for each fold.

Example:
- input: data = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]), k = 5
- output: [[[[3, 4], [5, 6], [7, 8], [9, 10]], [[1, 2]]],
        [[[1, 2], [5, 6], [7, 8], [9, 10]], [[3, 4]]],
        [[[1, 2], [3, 4], [7, 8], [9, 10]], [[5, 6]]], 
        [[[1, 2], [3, 4], [5, 6], [9, 10]], [[7, 8]]], 
        [[[1, 2], [3, 4], [5, 6], [7, 8]], [[9, 10]]]]
- reasoning: The dataset is divided into 5 parts, each being used once as a test set while the remaining parts serve as the training set.

In [ ]:
import numpy as np

def cross_validation_split(data: np.ndarray, k: int, seed=42) -> list:
    np.random.seed(seed)
    np.random.shuffle(data)

    n, m = data.shape
    sub_size = int(np.ceil(n / k))              # REMEMBER
    folds = []

    for i in range(k):
        start = i * sub_size                    # REMEMBER
        end = min((i + 1) * sub_size, n)        # REMEMBER
        validation = data[start:end]
        training = np.concatenate([data[:start], data[end:]], axis=0)
        folds.append((training, validation))

    return folds

In [2]:
data = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
k = 5

In [3]:
cross_validation_split(data, k)

[(array([[ 9, 10],
         [ 5,  6],
         [ 1,  2],
         [ 7,  8]]),
  array([[3, 4]])),
 (array([[3, 4],
         [5, 6],
         [1, 2],
         [7, 8]]),
  array([[ 9, 10]])),
 (array([[ 3,  4],
         [ 9, 10],
         [ 1,  2],
         [ 7,  8]]),
  array([[5, 6]])),
 (array([[ 3,  4],
         [ 9, 10],
         [ 5,  6],
         [ 7,  8]]),
  array([[1, 2]])),
 (array([[ 3,  4],
         [ 9, 10],
         [ 5,  6],
         [ 1,  2]]),
  array([[7, 8]]))]